# Generated by Django 2.1.5 on 2019-09-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20190916_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(),
        ),
    ]
