# Generated by Django 2.1.5 on 2019-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20190916_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='usb',
            field=models.BooleanField(),
        ),
    ]
