# Generated by Django 2.1.5 on 2019-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20190916_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
    ]
