# Generated by Django 2.1.5 on 2019-09-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20190916_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='autofocus',
            field=models.BooleanField(verbose_name='Автофокусировка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='chip',
            field=models.CharField(max_length=200, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='flash',
            field=models.BooleanField(verbose_name='Вспышка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='fm_radio',
            field=models.BooleanField(verbose_name='FM-радио'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='front_camera',
            field=models.IntegerField(verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='main_сamera',
            field=models.IntegerField(verbose_name='Основная камера'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='mp3_player',
            field=models.BooleanField(verbose_name='MP3 плеер'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='operating_memory_capacity',
            field=models.IntegerField(verbose_name='Объем оперативной памяти (Гб)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(max_length=200, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_resolution',
            field=models.CharField(max_length=200, verbose_name='Разрешение дисплея'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(verbose_name='Размер дисплея'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sim_card_type',
            field=models.CharField(max_length=200, verbose_name='Тип SIM-карты'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sim_cards_quantity',
            field=models.IntegerField(verbose_name='Количество SIM-карт'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage_capacity',
            field=models.IntegerField(verbose_name='Объем встроенной памяти (Гб)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='usb',
            field=models.BooleanField(verbose_name='Интерфейс USB'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='water_dust_resistance',
            field=models.BooleanField(verbose_name='Защита от пыли и влаги'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='weight',
            field=models.IntegerField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='wireless_charging',
            field=models.BooleanField(verbose_name='Функция беспроводной зарядки'),
        ),
    ]
