# Generated by Django 2.1.5 on 2019-09-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_auto_20190917_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applefeatures',
            name='barometer',
        ),
        migrations.RemoveField(
            model_name='applefeatures',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='applefeatures',
            name='three_axis_gyroscope',
        ),
        migrations.RemoveField(
            model_name='applefeatures',
            name='unblock_by_face',
        ),
        migrations.RemoveField(
            model_name='ginzzufeatures',
            name='built_in_flashlight',
        ),
        migrations.RemoveField(
            model_name='ginzzufeatures',
            name='geomagnetic_sensor',
        ),
        migrations.RemoveField(
            model_name='ginzzufeatures',
            name='shockproof_case',
        ),
        migrations.RemoveField(
            model_name='ginzzufeatures',
            name='voice_recorder',
        ),
        migrations.RemoveField(
            model_name='motorolafeatures',
            name='headphone_jack_3_5',
        ),
        migrations.AddField(
            model_name='applefeatures',
            name='apple_feature',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ginzzufeatures',
            name='ginzzu_feature',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='motorolafeatures',
            name='motorola_feature',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
