# Generated by Django 2.1.5 on 2019-09-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20190917_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applefeatures',
            old_name='apple_feature',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='ginzzufeatures',
            old_name='ginzzu_feature',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='motorolafeatures',
            old_name='motorola_feature',
            new_name='feature',
        ),
    ]
