# Generated by Django 2.1.5 on 2019-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191001_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
