# Generated by Django 2.1.5 on 2019-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191001_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
